import React from 'react'

// Fonts
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

// Style
import './assets/styles/globals.css'

const FONT_PATH = './assets/fonts'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const avantGarde = localFont({
  variable: '--font-avant',
  src: [
    {
      path: `${FONT_PATH}/avant-garde-normal.ttf`,
      weight: '400',
      style: 'normal',
    },
    {
      path: `${FONT_PATH}/avant-garde-book.ttf`,
      weight: '300',
      style: 'normal',
    },
    {
      path: `${FONT_PATH}/avant-garde-book-oblique.ttf`,
      weight: '300',
      style: 'italic',
    },
    {
      path: `${FONT_PATH}/avant-garde-demi.ttf`,
      weight: '500',
      style: 'bold',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${avantGarde.className}`}>{children}</body>
    </html>
  )
}
